version: '3.7'
services:
  resources_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=resources
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - database-data:/var/lib/postgresql/data/
  resources-localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
      - 4571:4571
  activemq:
    image: rmohr/activemq:5.15.9-alpine
    volumes:
      - './activemq/conf/activemq.xml:/opt/apache-activemq-5.15.9/conf/activemq.xml'
    networks:
      - default
    ports:
      - "61616:61616" # broker (admin:adminactivemq)(amq:amq)
      - "8161:8161"   # web    http://boot2docker:8161/admin (admin:admin)
volumes:
  database-data: